name = "StippleMathjs"
uuid = "7fb1dcd0-db8f-4201-9509-3dea5d7792e9"
authors = ["Helmut Hänsel <helmut.haensel@gmx.de>"]
version = "1.0.0"

[deps]
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"

[compat]
Stipple = "0.28 - 0.31, 1"
julia = "1.6"

[extras]
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StippleUI"]
